[package]
name = "infinity"
version = "0.1.0"
authors = ["Andrea Lattuada <andrea.lattuada@inf.ethz.ch>"]

build = "build.rs"
links = "infinity"

[dependencies]

[build-dependencies]
bindgen = "0.36"
